-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activities
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    parent_id integer,
    CONSTRAINT activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_log_operators
(
    audit_log_id bigint NOT NULL,
    operator_id integer NOT NULL,
    CONSTRAINT audit_log_operators_pkey PRIMARY KEY (audit_log_id, operator_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id bigserial NOT NULL,
    action character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_id bigint NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctors
(
    id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT doctors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.domain_activities
(
    domain_id integer NOT NULL,
    activity_id integer NOT NULL,
    CONSTRAINT domain_activities_pkey PRIMARY KEY (domain_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.domains
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT domains_pkey PRIMARY KEY (id),
    CONSTRAINT domains_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.modification_requests
(
    id bigserial NOT NULL,
    registration_id bigint NOT NULL,
    operator_id integer NOT NULL,
    new_activity_date date,
    new_duration_minutes integer,
    new_session_id integer,
    new_doctor_id integer,
    reason text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    submitted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    handled_by_admin_id integer,
    handled_at timestamp without time zone,
    rejection_reason text COLLATE pg_catalog."default",
    CONSTRAINT modification_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.operators
(
    id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(120) COLLATE pg_catalog."default",
    CONSTRAINT operators_pkey PRIMARY KEY (id),
    CONSTRAINT operators_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_code_key UNIQUE (code),
    CONSTRAINT projects_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.registration_activities
(
    registration_id bigint NOT NULL,
    activity_id integer NOT NULL,
    CONSTRAINT registration_activities_pkey PRIMARY KEY (registration_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.registration_operators
(
    registration_id bigint NOT NULL,
    operator_id integer NOT NULL,
    CONSTRAINT registration_operators_pkey PRIMARY KEY (registration_id, operator_id)
);

CREATE TABLE IF NOT EXISTS public.registration_subjects
(
    registration_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    CONSTRAINT registration_subjects_pkey PRIMARY KEY (registration_id, subject_id)
);

CREATE TABLE IF NOT EXISTS public.registrations
(
    id bigserial NOT NULL,
    project_id integer NOT NULL,
    domain_id integer NOT NULL,
    session_id integer NOT NULL,
    doctor_id integer,
    activity_date date NOT NULL,
    duration_minutes integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT registrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL,
    session character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_session_key UNIQUE (session)
);

CREATE TABLE IF NOT EXISTS public.subject_types
(
    id serial NOT NULL,
    type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subject_types_pkey PRIMARY KEY (id),
    CONSTRAINT subject_types_type_key UNIQUE (type)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    id bigserial NOT NULL,
    project_id integer NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subject_type_id integer NOT NULL,
    CONSTRAINT subjects_pkey PRIMARY KEY (id),
    CONSTRAINT uk_subject_project_code UNIQUE (project_id, code)
);

ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES public.activities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_log_operators
    ADD CONSTRAINT audit_log_operators_audit_log_id_fkey FOREIGN KEY (audit_log_id)
        REFERENCES public.audit_logs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_log_operators
    ADD CONSTRAINT audit_log_operators_operator_id_fkey FOREIGN KEY (operator_id)
        REFERENCES public.operators (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.domain_activities
    ADD CONSTRAINT domain_activities_activity_id_fkey FOREIGN KEY (activity_id)
        REFERENCES public.activities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.domain_activities
    ADD CONSTRAINT domain_activities_domain_id_fkey FOREIGN KEY (domain_id)
        REFERENCES public.domains (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.modification_requests
    ADD CONSTRAINT modification_requests_handled_by_admin_id_fkey FOREIGN KEY (handled_by_admin_id)
        REFERENCES public.operators (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.modification_requests
    ADD CONSTRAINT modification_requests_new_doctor_id_fkey FOREIGN KEY (new_doctor_id)
        REFERENCES public.doctors (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.modification_requests
    ADD CONSTRAINT modification_requests_new_session_id_fkey FOREIGN KEY (new_session_id)
        REFERENCES public.sessions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.modification_requests
    ADD CONSTRAINT modification_requests_operator_id_fkey FOREIGN KEY (operator_id)
        REFERENCES public.operators (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.modification_requests
    ADD CONSTRAINT modification_requests_registration_id_fkey FOREIGN KEY (registration_id)
        REFERENCES public.registrations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_activities
    ADD CONSTRAINT registration_activities_activity_id_fkey FOREIGN KEY (activity_id)
        REFERENCES public.activities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_activities
    ADD CONSTRAINT registration_activities_registration_id_fkey FOREIGN KEY (registration_id)
        REFERENCES public.registrations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_operators
    ADD CONSTRAINT registration_operators_operator_id_fkey FOREIGN KEY (operator_id)
        REFERENCES public.operators (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_operators
    ADD CONSTRAINT registration_operators_registration_id_fkey FOREIGN KEY (registration_id)
        REFERENCES public.registrations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_subjects
    ADD CONSTRAINT registration_subjects_registration_id_fkey FOREIGN KEY (registration_id)
        REFERENCES public.registrations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registration_subjects
    ADD CONSTRAINT registration_subjects_subject_id_fkey FOREIGN KEY (subject_id)
        REFERENCES public.subjects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.registrations
    ADD CONSTRAINT registrations_doctor_id_fkey FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrations
    ADD CONSTRAINT registrations_domain_id_fkey FOREIGN KEY (domain_id)
        REFERENCES public.domains (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrations
    ADD CONSTRAINT registrations_project_id_fkey FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrations
    ADD CONSTRAINT registrations_session_id_fkey FOREIGN KEY (session_id)
        REFERENCES public.sessions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subjects
    ADD CONSTRAINT subjects_project_id_fkey FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subjects
    ADD CONSTRAINT subjects_subject_type_id_fkey FOREIGN KEY (subject_type_id)
        REFERENCES public.subject_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;