-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(120) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    registration_id bigint NOT NULL,
    admin_id bigint NOT NULL,
    action character varying(255) COLLATE pg_catalog."default" NOT NULL,
    json_details_registration bigint NOT NULL,
    date_time timestamp without time zone NOT NULL,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.domain
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT domain_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.operator_registration
(
    registration_id bigint NOT NULL,
    researcher_id bigint NOT NULL,
    CONSTRAINT operator_registration_pkey PRIMARY KEY (registration_id, researcher_id)
    );

CREATE TABLE IF NOT EXISTS public.patient
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    patient_code integer NOT NULL,
    project_id bigint NOT NULL,
    subject_type_id bigint NOT NULL,
    CONSTRAINT paziente_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.project
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    acronym character varying(5) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT project_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.referring_doctor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    gender "char",
    CONSTRAINT referring_doctor_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.registration
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    domain_id bigint NOT NULL,
    project_id bigint NOT NULL,
    date date,
    duration_minutes integer NOT NULL,
    session text COLLATE pg_catalog."default" NOT NULL,
    referring_doctor_id bigint,
    subject_type_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone,
    is_modified boolean NOT NULL DEFAULT false,
    CONSTRAINT registration_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.registration_subject
(
    registration_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    CONSTRAINT registration_subject_pkey PRIMARY KEY (registration_id, patient_id)
    );

CREATE TABLE IF NOT EXISTS public.request_modification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    registration_id bigint NOT NULL,
    requesting_researcher_id bigint NOT NULL,
    description_edit text COLLATE pg_catalog."default" NOT NULL,
    state "char" NOT NULL,
    requested_date date NOT NULL,
    admin_manager bigint NOT NULL,
    CONSTRAINT request_modification_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.researcher
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    is_student boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT ricercatore_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.subject_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT subject_type_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.test
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.test_registration
(
    registration_id bigint NOT NULL,
    test_id bigint NOT NULL,
    CONSTRAINT test_registration_pkey PRIMARY KEY (registration_id, test_id)
    );

CREATE TABLE IF NOT EXISTS public.test_to_domain
(
    test_id bigint NOT NULL,
    domain_id bigint NOT NULL,
    CONSTRAINT test_to_domain_pkey PRIMARY KEY (test_id, domain_id)
    );

ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT fk_admin_id FOREIGN KEY (admin_id)
    REFERENCES public.admin (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT fk_json_details_registration FOREIGN KEY (json_details_registration)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT fk_registration_id FOREIGN KEY (registration_id)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.operator_registration
    ADD CONSTRAINT fk_registration_id FOREIGN KEY (registration_id)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.operator_registration
    ADD CONSTRAINT fk_researcher_id FOREIGN KEY (researcher_id)
    REFERENCES public.researcher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT fk_project_id FOREIGN KEY (project_id)
    REFERENCES public.project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT fk_subject_type_id FOREIGN KEY (subject_type_id)
    REFERENCES public.subject_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.registration
    ADD CONSTRAINT fk_domain_id FOREIGN KEY (domain_id)
    REFERENCES public.domain (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registration
    ADD CONSTRAINT fk_project_id FOREIGN KEY (project_id)
    REFERENCES public.project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registration
    ADD CONSTRAINT fk_referring_doctor_id FOREIGN KEY (referring_doctor_id)
    REFERENCES public.referring_doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registration
    ADD CONSTRAINT fk_subject_type_id FOREIGN KEY (subject_type_id)
    REFERENCES public.subject_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registration_subject
    ADD CONSTRAINT fk_patient_id FOREIGN KEY (patient_id)
    REFERENCES public.patient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registration_subject
    ADD CONSTRAINT fk_registration_id FOREIGN KEY (registration_id)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.request_modification
    ADD CONSTRAINT fk_admin_manager FOREIGN KEY (admin_manager)
    REFERENCES public.admin (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.request_modification
    ADD CONSTRAINT fk_registration_id FOREIGN KEY (registration_id)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.request_modification
    ADD CONSTRAINT fk_requesting_researcher_id FOREIGN KEY (requesting_researcher_id)
    REFERENCES public.researcher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.test_registration
    ADD CONSTRAINT fk_registration_id FOREIGN KEY (registration_id)
    REFERENCES public.registration (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.test_registration
    ADD CONSTRAINT fk_test_id FOREIGN KEY (test_id)
    REFERENCES public.test (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.test_to_domain
    ADD CONSTRAINT fk_domain_id FOREIGN KEY (domain_id)
    REFERENCES public.domain (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test_to_domain
    ADD CONSTRAINT fk_test_id FOREIGN KEY (test_id)
    REFERENCES public.test (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;